In [1]:
import pandas as pd
import numpy as np
mydata=pd.read_csv(('hospital.csv'))
mydata

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [2]:
mydata.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
restecg       int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [3]:
mydata.shape

(303, 14)

In [4]:
mydata.drop_duplicates(inplace=True)
mydata.shape

(302, 14)

In [5]:
mydata=pd.get_dummies(mydata,columns=['restecg']) # run without this line
mydata

age  sex  cp  trtbps  chol  fbs  thalachh  exng  oldpeak  slp  caa  \
0     63    1   3     145   233    1       150     0      2.3    0    0   
1     37    1   2     130   250    0       187     0      3.5    0    0   
2     41    0   1     130   204    0       172     0      1.4    2    0   
3     56    1   1     120   236    0       178     0      0.8    2    0   
4     57    0   0     120   354    0       163     1      0.6    2    0   
..   ...  ...  ..     ...   ...  ...       ...   ...      ...  ...  ...   
298   57    0   0     140   241    0       123     1      0.2    1    0   
299   45    1   3     110   264    0       132     0      1.2    1    0   
300   68    1   0     144   193    1       141     0      3.4    1    2   
301   57    1   0     130   131    0       115     1      1.2    1    1   
302   57    0   1     130   236    0       174     0      0.0    1    1   

     thall  output  restecg_0  restecg_1  restecg_2  
0        1       1          1          0          0  
1        2       1          0          1          0  
2        2       1          1          0          0  
3        2       1          0          1          0  
4        2       1          0          1          0  
..     ...     ...        ...        ...        ...  
298      3       0          0          1          0  
299      3       0          0          1          0  
300      3       0          0          1          0  
301      3       0          0          1          0  
302      2       0          1          0          0  

[302 rows x 16 columns]

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

In [59]:
mydata.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'thalachh', 'exng',
       'oldpeak', 'slp', 'caa', 'thall', 'output', 'restecg_0', 'restecg_1',
       'restecg_2'],
      dtype='object')

In [58]:
label=[]
for i in mydata.columns:
    if i !='output' :
        label.append(i)
x=np.asarray(mydata[label])
y = np.asarray(mydata['output'])
print(x)
print(y)

[[63.  1.  3. ...  1.  0.  0.]
 [37.  1.  2. ...  0.  1.  0.]
 [41.  0.  1. ...  1.  0.  0.]
 ...
 [68.  1.  0. ...  0.  1.  0.]
 [57.  1.  0. ...  0.  1.  0.]
 [57.  0.  1. ...  1.  0.  0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [57]:
from sklearn.preprocessing import scale,normalize,minmax_scale
#x=minmax_scale(x,feature_range=(-1,1))
#x=normalize(x,norm='l2',axis=0)
x=scale(x)

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,
                                    random_state=42,stratify=mydata.sex)
p_grid={'n_neighbors':np.arange(2,50)}
knn=KNeighborsClassifier()
knn_cv=GridSearchCV(knn,p_grid,cv =5)
knn_cv.fit(x,y)
print(knn_cv.best_params_)
print(knn_cv.best_score_)
#print(knn_cv.cv_results_)

{'n_neighbors': 14}
0.8375956284153006
{'mean_fit_time': array([0.00179596, 0.00180202, 0.00201125, 0.00369968, 0.00162268,
       0.00201616, 0.00322089, 0.        , 0.00361462, 0.0016057 ,
       0.00040412, 0.00040398, 0.00040388, 0.00161066, 0.00040522,
       0.00040526, 0.00201077, 0.00040603, 0.00160484, 0.00161209,
       0.0004046 , 0.00321031, 0.00201554, 0.00040655, 0.00200958,
       0.00161042, 0.00040512, 0.00321774, 0.00201006, 0.00081015,
       0.00099745, 0.0009974 , 0.00140481, 0.00040383, 0.00242186,
       0.00160513, 0.00080342, 0.00120225, 0.00161576, 0.00200853,
       0.00080814, 0.        , 0.00322185, 0.0016149 , 0.0020124 ,
       0.        , 0.003228  , 0.        , 0.        ]), 'std_fit_time': array([1.16285938e-03, 1.83985414e-03, 3.11229332e-03, 3.77937002e-03,
       3.24535370e-03, 3.12401715e-03, 3.94477236e-03, 0.00000000e+00,
       3.67593105e-03, 3.21140289e-03, 8.08238983e-04, 8.07952881e-04,
       8.07762146e-04, 3.22132111e-03, 8.10432434e-04,

In [10]:
knn=KNeighborsClassifier(n_neighbors=14)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
knn_score=knn.score(x_test,y_test)
print('knn_score test: %f' %knn_score)
knn_score=knn.score(x_train,y_train)
print('knn_score train: %f' %knn_score)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

knn_score test: 0.840000
knn_score train: 0.846535
[[35 12]
 [ 4 49]]
              precision    recall  f1-score   support

           0       0.90      0.74      0.81        47
           1       0.80      0.92      0.86        53

    accuracy                           0.84       100
   macro avg       0.85      0.83      0.84       100
weighted avg       0.85      0.84      0.84       100



In [11]:
Accuracy = metrics.accuracy_score(y_test,y_pred)
Accuracy

0.84

In [12]:
Precision = metrics.precision_score(y_test,y_pred)
Precision

0.8032786885245902

In [13]:
Sensitivity_recall = metrics.recall_score(y_test,y_pred)
Sensitivity_recall

0.9245283018867925

In [14]:
F1_score = metrics.f1_score(y_test,y_pred)
F1_score

0.8596491228070176

In [15]:
from sklearn.model_selection import cross_validate

In [16]:
cv_results = cross_validate(knn, x, y, cv=10,return_train_score=True)

In [17]:
cv_results['test_score'].mean()

0.8210752688172043

In [18]:
cv_results['train_score'].mean()

0.844006403299327

In [19]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [20]:
y_pred_prob=knn.predict_proba(x_test)[:,1]
roc_auc_score(y_test,y_pred_prob)

0.9140907266158169

In [21]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train, y_train)
y_pred=lr.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
lr_score=lr.score(x_test,y_test)
print('lr_score test: %f' %lr_score)
lr_score=lr.score(x_train,y_train)
print('lr_score train: %f' %lr_score)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

lr_score test: 0.800000
lr_score train: 0.866337
[[31 16]
 [ 4 49]]
              precision    recall  f1-score   support

           0       0.89      0.66      0.76        47
           1       0.75      0.92      0.83        53

    accuracy                           0.80       100
   macro avg       0.82      0.79      0.79       100
weighted avg       0.82      0.80      0.80       100



In [22]:
Accuracy = metrics.accuracy_score(y_test,y_pred)
Accuracy

0.8

In [23]:
Precision = metrics.precision_score(y_test,y_pred)
Precision

0.7538461538461538

In [24]:
Sensitivity_recall = metrics.recall_score(y_test,y_pred)
Sensitivity_recall

0.9245283018867925

In [25]:
F1_score = metrics.f1_score(y_test,y_pred)
F1_score

0.8305084745762712

In [26]:
y_pred_prob=lr.predict_proba(x_test)[:,1]
roc_auc_score(y_test,y_pred_prob)

0.9016459253311923

In [27]:
cv_results = cross_validate(lr, x, y, cv=10,return_train_score=True)

In [28]:
cv_results['test_score'].mean()

0.8210752688172043

In [29]:
cv_results['train_score'].mean()

0.850625406989364

In [30]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='rbf')
svclassifier.fit(x_train,y_train)
svc_score_test=svclassifier.score(x_test,y_test)
print('svc_score test: %f' %svc_score_test)
svc_score_train=svclassifier.score(x_train,y_train)
print('svc_score train: %f' %svc_score_train)
y_pred=svclassifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

svc_score test: 0.800000
svc_score train: 0.915842
[[30 17]
 [ 3 50]]
              precision    recall  f1-score   support

           0       0.91      0.64      0.75        47
           1       0.75      0.94      0.83        53

    accuracy                           0.80       100
   macro avg       0.83      0.79      0.79       100
weighted avg       0.82      0.80      0.79       100



In [31]:
Accuracy = metrics.accuracy_score(y_test,y_pred)
Accuracy

0.8

In [32]:
Precision = metrics.precision_score(y_test,y_pred)
Precision

0.746268656716418

In [33]:
Sensitivity_recall = metrics.recall_score(y_test,y_pred)
Sensitivity_recall

0.9433962264150944

In [34]:
F1_score = metrics.f1_score(y_test,y_pred)
F1_score

0.8333333333333333

In [35]:
cv_results = cross_validate(svclassifier, x, y, cv=10,return_train_score=True)

In [36]:
cv_results['test_score'].mean()

0.8210752688172043

In [37]:
cv_results['train_score'].mean()

0.9146421206859128

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
drugtree=DecisionTreeClassifier(criterion='entropy' ,max_depth=4)
drugtree.fit(x_train, y_train)
predtree=drugtree.predict(x_test)
print(predtree[:5])
print(y_test[:5])

[0 0 0 1 0]
[1 0 0 1 0]


In [40]:
print(confusion_matrix(y_test, predtree))
print(classification_report(y_test, predtree))

[[31 16]
 [ 7 46]]
              precision    recall  f1-score   support

           0       0.82      0.66      0.73        47
           1       0.74      0.87      0.80        53

    accuracy                           0.77       100
   macro avg       0.78      0.76      0.76       100
weighted avg       0.78      0.77      0.77       100



In [41]:
drugtree_score=drugtree.score(x_test,y_test)
print('drugtree_score test: %f' %drugtree_score)
drugtree_score=drugtree.score(x_train,y_train)
print('drugtree_score train: %f' %drugtree_score)

drugtree_score test: 0.770000
drugtree_score train: 0.886139


In [42]:
Accuracy = metrics.accuracy_score(y_test,y_pred)
Accuracy

0.8

In [43]:
Precision = metrics.precision_score(y_test,y_pred)
Precision

0.746268656716418

In [44]:
Sensitivity_recall = metrics.recall_score(y_test,y_pred)
Sensitivity_recall

0.9433962264150944

In [45]:
F1_score = metrics.f1_score(y_test,y_pred)
F1_score

0.8333333333333333

In [46]:
y_pred_prob=drugtree.predict_proba(x_test)[:,1]
roc_auc_score(y_test,y_pred_prob)

0.8223604977920513

In [47]:
cv_results = cross_validate(drugtree, x, y, cv=10,return_train_score=True)

In [48]:
cv_results['test_score'].mean()

0.7750537634408602

In [49]:
cv_results['train_score'].mean()

0.8734385174734101

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
models={'Decision Tree':DecisionTreeClassifier(),
       'Logestic Regression':LogisticRegression(),
       'Random forest':RandomForestClassifier(),
       'Adaboost':AdaBoostClassifier()}
for name,model in models.items():
    scores=cross_val_score(model,x,y,cv=10,scoring='f1_weighted')
    print(name,scores,scores.mean())

Decision Tree [0.80685484 0.83904675 0.79722222 0.8338945  0.8        0.63210975
 0.69899889 0.73333333 0.6989899  0.76266667] 0.7603116851995421
Logestic Regression [0.86700623 0.80438379 0.83238095 0.9003367  0.83277217 0.79821429
 0.86546003 0.86546003 0.68766157 0.73092006] 0.8184595813314461
Random forest [0.90134263 0.83802697 0.86666667 0.93363095 0.89828571 0.83277716
 0.76588103 0.83047619 0.72592593 0.76588103] 0.8358894274652803
Adaboost [0.90134263 0.83802697 0.7674523  0.93363095 0.86296296 0.79821429
 0.76588103 0.8        0.73092006 0.76266667] 0.8161097861404787


In [51]:
randomforest=RandomForestClassifier()
randomforest.fit(x_train,y_train)
rf_prid=randomforest.predict(x_test)
print(confusion_matrix(y_test, rf_prid))
print(classification_report(y_test, rf_prid))

[[32 15]
 [ 3 50]]
              precision    recall  f1-score   support

           0       0.91      0.68      0.78        47
           1       0.77      0.94      0.85        53

    accuracy                           0.82       100
   macro avg       0.84      0.81      0.81       100
weighted avg       0.84      0.82      0.82       100



In [52]:
randomforest_score=randomforest.score(x_test,y_test)
print('randomforest_score test: %f' %randomforest_score)
randomforest_score=randomforest.score(x_train,y_train)
print('randomforest_score train: %f' %randomforest_score)

randomforest_score test: 0.820000
randomforest_score train: 1.000000


In [53]:
cv_results = cross_validate(randomforest, x, y, cv=10,return_train_score=True)

In [54]:
sorted(cv_results.keys())

['fit_time', 'score_time', 'test_score', 'train_score']

In [55]:
cv_results['test_score'].mean()

0.8343010752688171

In [56]:
cv_results['train_score'].mean()

1.0